// Generated by gencpp from file bboat_pkg/gain_serv.msg
// DO NOT EDIT!


#ifndef BBOAT_PKG_MESSAGE_GAIN_SERV_H
#define BBOAT_PKG_MESSAGE_GAIN_SERV_H

#include <ros/service_traits.h>


#include <bboat_pkg/gain_servRequest.h>
#include <bboat_pkg/gain_servResponse.h>


namespace bboat_pkg
{

struct gain_serv
{

typedef gain_servRequest Request;
typedef gain_servResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gain_serv
} // namespace bboat_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bboat_pkg::gain_serv > {
  static const char* value()
  {
    return "5f632b8cb09f5ccd1ae01e67f49049ea";
  }

  static const char* value(const ::bboat_pkg::gain_serv&) { return value(); }
};

template<>
struct DataType< ::bboat_pkg::gain_serv > {
  static const char* value()
  {
    return "bboat_pkg/gain_serv";
  }

  static const char* value(const ::bboat_pkg::gain_serv&) { return value(); }
};


// service_traits::MD5Sum< ::bboat_pkg::gain_servRequest> should match
// service_traits::MD5Sum< ::bboat_pkg::gain_serv >
template<>
struct MD5Sum< ::bboat_pkg::gain_servRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bboat_pkg::gain_serv >::value();
  }
  static const char* value(const ::bboat_pkg::gain_servRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bboat_pkg::gain_servRequest> should match
// service_traits::DataType< ::bboat_pkg::gain_serv >
template<>
struct DataType< ::bboat_pkg::gain_servRequest>
{
  static const char* value()
  {
    return DataType< ::bboat_pkg::gain_serv >::value();
  }
  static const char* value(const ::bboat_pkg::gain_servRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bboat_pkg::gain_servResponse> should match
// service_traits::MD5Sum< ::bboat_pkg::gain_serv >
template<>
struct MD5Sum< ::bboat_pkg::gain_servResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bboat_pkg::gain_serv >::value();
  }
  static const char* value(const ::bboat_pkg::gain_servResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bboat_pkg::gain_servResponse> should match
// service_traits::DataType< ::bboat_pkg::gain_serv >
template<>
struct DataType< ::bboat_pkg::gain_servResponse>
{
  static const char* value()
  {
    return DataType< ::bboat_pkg::gain_serv >::value();
  }
  static const char* value(const ::bboat_pkg::gain_servResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BBOAT_PKG_MESSAGE_GAIN_SERV_H
