// Generated by gencpp from file bboat_pkg/lambert_ref_servResponse.msg
// DO NOT EDIT!


#ifndef BBOAT_PKG_MESSAGE_LAMBERT_REF_SERVRESPONSE_H
#define BBOAT_PKG_MESSAGE_LAMBERT_REF_SERVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace bboat_pkg
{
template <class ContainerAllocator>
struct lambert_ref_servResponse_
{
  typedef lambert_ref_servResponse_<ContainerAllocator> Type;

  lambert_ref_servResponse_()
    : lambert_ref()  {
    }
  lambert_ref_servResponse_(const ContainerAllocator& _alloc)
    : lambert_ref(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _lambert_ref_type;
  _lambert_ref_type lambert_ref;





  typedef boost::shared_ptr< ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator> const> ConstPtr;

}; // struct lambert_ref_servResponse_

typedef ::bboat_pkg::lambert_ref_servResponse_<std::allocator<void> > lambert_ref_servResponse;

typedef boost::shared_ptr< ::bboat_pkg::lambert_ref_servResponse > lambert_ref_servResponsePtr;
typedef boost::shared_ptr< ::bboat_pkg::lambert_ref_servResponse const> lambert_ref_servResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator1> & lhs, const ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator2> & rhs)
{
  return lhs.lambert_ref == rhs.lambert_ref;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator1> & lhs, const ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bboat_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9a86cd1b06af5288af973c72e093b29";
  }

  static const char* value(const ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9a86cd1b06af528ULL;
  static const uint64_t static_value2 = 0x8af973c72e093b29ULL;
};

template<class ContainerAllocator>
struct DataType< ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bboat_pkg/lambert_ref_servResponse";
  }

  static const char* value(const ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point lambert_ref\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lambert_ref);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lambert_ref_servResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bboat_pkg::lambert_ref_servResponse_<ContainerAllocator>& v)
  {
    s << indent << "lambert_ref: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.lambert_ref);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BBOAT_PKG_MESSAGE_LAMBERT_REF_SERVRESPONSE_H
