// Generated by gencpp from file bboat_pkg/lambert_ref_serv.msg
// DO NOT EDIT!


#ifndef BBOAT_PKG_MESSAGE_LAMBERT_REF_SERV_H
#define BBOAT_PKG_MESSAGE_LAMBERT_REF_SERV_H

#include <ros/service_traits.h>


#include <bboat_pkg/lambert_ref_servRequest.h>
#include <bboat_pkg/lambert_ref_servResponse.h>


namespace bboat_pkg
{

struct lambert_ref_serv
{

typedef lambert_ref_servRequest Request;
typedef lambert_ref_servResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct lambert_ref_serv
} // namespace bboat_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bboat_pkg::lambert_ref_serv > {
  static const char* value()
  {
    return "2f9744e749801011d7a2f5581e48ef29";
  }

  static const char* value(const ::bboat_pkg::lambert_ref_serv&) { return value(); }
};

template<>
struct DataType< ::bboat_pkg::lambert_ref_serv > {
  static const char* value()
  {
    return "bboat_pkg/lambert_ref_serv";
  }

  static const char* value(const ::bboat_pkg::lambert_ref_serv&) { return value(); }
};


// service_traits::MD5Sum< ::bboat_pkg::lambert_ref_servRequest> should match
// service_traits::MD5Sum< ::bboat_pkg::lambert_ref_serv >
template<>
struct MD5Sum< ::bboat_pkg::lambert_ref_servRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bboat_pkg::lambert_ref_serv >::value();
  }
  static const char* value(const ::bboat_pkg::lambert_ref_servRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bboat_pkg::lambert_ref_servRequest> should match
// service_traits::DataType< ::bboat_pkg::lambert_ref_serv >
template<>
struct DataType< ::bboat_pkg::lambert_ref_servRequest>
{
  static const char* value()
  {
    return DataType< ::bboat_pkg::lambert_ref_serv >::value();
  }
  static const char* value(const ::bboat_pkg::lambert_ref_servRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bboat_pkg::lambert_ref_servResponse> should match
// service_traits::MD5Sum< ::bboat_pkg::lambert_ref_serv >
template<>
struct MD5Sum< ::bboat_pkg::lambert_ref_servResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bboat_pkg::lambert_ref_serv >::value();
  }
  static const char* value(const ::bboat_pkg::lambert_ref_servResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bboat_pkg::lambert_ref_servResponse> should match
// service_traits::DataType< ::bboat_pkg::lambert_ref_serv >
template<>
struct DataType< ::bboat_pkg::lambert_ref_servResponse>
{
  static const char* value()
  {
    return DataType< ::bboat_pkg::lambert_ref_serv >::value();
  }
  static const char* value(const ::bboat_pkg::lambert_ref_servResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BBOAT_PKG_MESSAGE_LAMBERT_REF_SERV_H
