// Generated by gencpp from file bboat_pkg/mode_serv.msg
// DO NOT EDIT!


#ifndef BBOAT_PKG_MESSAGE_MODE_SERV_H
#define BBOAT_PKG_MESSAGE_MODE_SERV_H

#include <ros/service_traits.h>


#include <bboat_pkg/mode_servRequest.h>
#include <bboat_pkg/mode_servResponse.h>


namespace bboat_pkg
{

struct mode_serv
{

typedef mode_servRequest Request;
typedef mode_servResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mode_serv
} // namespace bboat_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bboat_pkg::mode_serv > {
  static const char* value()
  {
    return "a6ec36370aeacdd14ee457803ad5dd8a";
  }

  static const char* value(const ::bboat_pkg::mode_serv&) { return value(); }
};

template<>
struct DataType< ::bboat_pkg::mode_serv > {
  static const char* value()
  {
    return "bboat_pkg/mode_serv";
  }

  static const char* value(const ::bboat_pkg::mode_serv&) { return value(); }
};


// service_traits::MD5Sum< ::bboat_pkg::mode_servRequest> should match
// service_traits::MD5Sum< ::bboat_pkg::mode_serv >
template<>
struct MD5Sum< ::bboat_pkg::mode_servRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bboat_pkg::mode_serv >::value();
  }
  static const char* value(const ::bboat_pkg::mode_servRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bboat_pkg::mode_servRequest> should match
// service_traits::DataType< ::bboat_pkg::mode_serv >
template<>
struct DataType< ::bboat_pkg::mode_servRequest>
{
  static const char* value()
  {
    return DataType< ::bboat_pkg::mode_serv >::value();
  }
  static const char* value(const ::bboat_pkg::mode_servRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bboat_pkg::mode_servResponse> should match
// service_traits::MD5Sum< ::bboat_pkg::mode_serv >
template<>
struct MD5Sum< ::bboat_pkg::mode_servResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bboat_pkg::mode_serv >::value();
  }
  static const char* value(const ::bboat_pkg::mode_servResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bboat_pkg::mode_servResponse> should match
// service_traits::DataType< ::bboat_pkg::mode_serv >
template<>
struct DataType< ::bboat_pkg::mode_servResponse>
{
  static const char* value()
  {
    return DataType< ::bboat_pkg::mode_serv >::value();
  }
  static const char* value(const ::bboat_pkg::mode_servResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BBOAT_PKG_MESSAGE_MODE_SERV_H
