// Generated by gencpp from file bboat_pkg/next_target_serv.msg
// DO NOT EDIT!


#ifndef BBOAT_PKG_MESSAGE_NEXT_TARGET_SERV_H
#define BBOAT_PKG_MESSAGE_NEXT_TARGET_SERV_H

#include <ros/service_traits.h>


#include <bboat_pkg/next_target_servRequest.h>
#include <bboat_pkg/next_target_servResponse.h>


namespace bboat_pkg
{

struct next_target_serv
{

typedef next_target_servRequest Request;
typedef next_target_servResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct next_target_serv
} // namespace bboat_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bboat_pkg::next_target_serv > {
  static const char* value()
  {
    return "d9ce4b52e25eaaef6e3a53a636b0b720";
  }

  static const char* value(const ::bboat_pkg::next_target_serv&) { return value(); }
};

template<>
struct DataType< ::bboat_pkg::next_target_serv > {
  static const char* value()
  {
    return "bboat_pkg/next_target_serv";
  }

  static const char* value(const ::bboat_pkg::next_target_serv&) { return value(); }
};


// service_traits::MD5Sum< ::bboat_pkg::next_target_servRequest> should match
// service_traits::MD5Sum< ::bboat_pkg::next_target_serv >
template<>
struct MD5Sum< ::bboat_pkg::next_target_servRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bboat_pkg::next_target_serv >::value();
  }
  static const char* value(const ::bboat_pkg::next_target_servRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bboat_pkg::next_target_servRequest> should match
// service_traits::DataType< ::bboat_pkg::next_target_serv >
template<>
struct DataType< ::bboat_pkg::next_target_servRequest>
{
  static const char* value()
  {
    return DataType< ::bboat_pkg::next_target_serv >::value();
  }
  static const char* value(const ::bboat_pkg::next_target_servRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bboat_pkg::next_target_servResponse> should match
// service_traits::MD5Sum< ::bboat_pkg::next_target_serv >
template<>
struct MD5Sum< ::bboat_pkg::next_target_servResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bboat_pkg::next_target_serv >::value();
  }
  static const char* value(const ::bboat_pkg::next_target_servResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bboat_pkg::next_target_servResponse> should match
// service_traits::DataType< ::bboat_pkg::next_target_serv >
template<>
struct DataType< ::bboat_pkg::next_target_servResponse>
{
  static const char* value()
  {
    return DataType< ::bboat_pkg::next_target_serv >::value();
  }
  static const char* value(const ::bboat_pkg::next_target_servResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BBOAT_PKG_MESSAGE_NEXT_TARGET_SERV_H
