// Generated by gencpp from file bboat_pkg/path_description_servRequest.msg
// DO NOT EDIT!


#ifndef BBOAT_PKG_MESSAGE_PATH_DESCRIPTION_SERVREQUEST_H
#define BBOAT_PKG_MESSAGE_PATH_DESCRIPTION_SERVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bboat_pkg
{
template <class ContainerAllocator>
struct path_description_servRequest_
{
  typedef path_description_servRequest_<ContainerAllocator> Type;

  path_description_servRequest_()
    {
    }
  path_description_servRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::bboat_pkg::path_description_servRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bboat_pkg::path_description_servRequest_<ContainerAllocator> const> ConstPtr;

}; // struct path_description_servRequest_

typedef ::bboat_pkg::path_description_servRequest_<std::allocator<void> > path_description_servRequest;

typedef boost::shared_ptr< ::bboat_pkg::path_description_servRequest > path_description_servRequestPtr;
typedef boost::shared_ptr< ::bboat_pkg::path_description_servRequest const> path_description_servRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bboat_pkg::path_description_servRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bboat_pkg::path_description_servRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace bboat_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bboat_pkg::path_description_servRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bboat_pkg::path_description_servRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bboat_pkg::path_description_servRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bboat_pkg::path_description_servRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bboat_pkg::path_description_servRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bboat_pkg::path_description_servRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bboat_pkg::path_description_servRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::bboat_pkg::path_description_servRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::bboat_pkg::path_description_servRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bboat_pkg/path_description_servRequest";
  }

  static const char* value(const ::bboat_pkg::path_description_servRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bboat_pkg::path_description_servRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::bboat_pkg::path_description_servRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bboat_pkg::path_description_servRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct path_description_servRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bboat_pkg::path_description_servRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::bboat_pkg::path_description_servRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // BBOAT_PKG_MESSAGE_PATH_DESCRIPTION_SERVREQUEST_H
