// Generated by gencpp from file bboat_pkg/path_description_serv.msg
// DO NOT EDIT!


#ifndef BBOAT_PKG_MESSAGE_PATH_DESCRIPTION_SERV_H
#define BBOAT_PKG_MESSAGE_PATH_DESCRIPTION_SERV_H

#include <ros/service_traits.h>


#include <bboat_pkg/path_description_servRequest.h>
#include <bboat_pkg/path_description_servResponse.h>


namespace bboat_pkg
{

struct path_description_serv
{

typedef path_description_servRequest Request;
typedef path_description_servResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct path_description_serv
} // namespace bboat_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bboat_pkg::path_description_serv > {
  static const char* value()
  {
    return "708adc44b97d996f881dbcca00b89ef2";
  }

  static const char* value(const ::bboat_pkg::path_description_serv&) { return value(); }
};

template<>
struct DataType< ::bboat_pkg::path_description_serv > {
  static const char* value()
  {
    return "bboat_pkg/path_description_serv";
  }

  static const char* value(const ::bboat_pkg::path_description_serv&) { return value(); }
};


// service_traits::MD5Sum< ::bboat_pkg::path_description_servRequest> should match
// service_traits::MD5Sum< ::bboat_pkg::path_description_serv >
template<>
struct MD5Sum< ::bboat_pkg::path_description_servRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bboat_pkg::path_description_serv >::value();
  }
  static const char* value(const ::bboat_pkg::path_description_servRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bboat_pkg::path_description_servRequest> should match
// service_traits::DataType< ::bboat_pkg::path_description_serv >
template<>
struct DataType< ::bboat_pkg::path_description_servRequest>
{
  static const char* value()
  {
    return DataType< ::bboat_pkg::path_description_serv >::value();
  }
  static const char* value(const ::bboat_pkg::path_description_servRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bboat_pkg::path_description_servResponse> should match
// service_traits::MD5Sum< ::bboat_pkg::path_description_serv >
template<>
struct MD5Sum< ::bboat_pkg::path_description_servResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bboat_pkg::path_description_serv >::value();
  }
  static const char* value(const ::bboat_pkg::path_description_servResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bboat_pkg::path_description_servResponse> should match
// service_traits::DataType< ::bboat_pkg::path_description_serv >
template<>
struct DataType< ::bboat_pkg::path_description_servResponse>
{
  static const char* value()
  {
    return DataType< ::bboat_pkg::path_description_serv >::value();
  }
  static const char* value(const ::bboat_pkg::path_description_servResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BBOAT_PKG_MESSAGE_PATH_DESCRIPTION_SERV_H
