// Generated by gencpp from file bboat_pkg/reset_lamb_servRequest.msg
// DO NOT EDIT!


#ifndef BBOAT_PKG_MESSAGE_RESET_LAMB_SERVREQUEST_H
#define BBOAT_PKG_MESSAGE_RESET_LAMB_SERVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bboat_pkg
{
template <class ContainerAllocator>
struct reset_lamb_servRequest_
{
  typedef reset_lamb_servRequest_<ContainerAllocator> Type;

  reset_lamb_servRequest_()
    : req(false)  {
    }
  reset_lamb_servRequest_(const ContainerAllocator& _alloc)
    : req(false)  {
  (void)_alloc;
    }



   typedef uint8_t _req_type;
  _req_type req;





  typedef boost::shared_ptr< ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator> const> ConstPtr;

}; // struct reset_lamb_servRequest_

typedef ::bboat_pkg::reset_lamb_servRequest_<std::allocator<void> > reset_lamb_servRequest;

typedef boost::shared_ptr< ::bboat_pkg::reset_lamb_servRequest > reset_lamb_servRequestPtr;
typedef boost::shared_ptr< ::bboat_pkg::reset_lamb_servRequest const> reset_lamb_servRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator1> & lhs, const ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator2> & rhs)
{
  return lhs.req == rhs.req;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator1> & lhs, const ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bboat_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be3c44e19d0c6b00b25e356c69155e2a";
  }

  static const char* value(const ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe3c44e19d0c6b00ULL;
  static const uint64_t static_value2 = 0xb25e356c69155e2aULL;
};

template<class ContainerAllocator>
struct DataType< ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bboat_pkg/reset_lamb_servRequest";
  }

  static const char* value(const ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool req\n"
;
  }

  static const char* value(const ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.req);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct reset_lamb_servRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bboat_pkg::reset_lamb_servRequest_<ContainerAllocator>& v)
  {
    s << indent << "req: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.req);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BBOAT_PKG_MESSAGE_RESET_LAMB_SERVREQUEST_H
