// Generated by gencpp from file bboat_pkg/reset_lamb_servResponse.msg
// DO NOT EDIT!


#ifndef BBOAT_PKG_MESSAGE_RESET_LAMB_SERVRESPONSE_H
#define BBOAT_PKG_MESSAGE_RESET_LAMB_SERVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bboat_pkg
{
template <class ContainerAllocator>
struct reset_lamb_servResponse_
{
  typedef reset_lamb_servResponse_<ContainerAllocator> Type;

  reset_lamb_servResponse_()
    : success(false)  {
    }
  reset_lamb_servResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator> const> ConstPtr;

}; // struct reset_lamb_servResponse_

typedef ::bboat_pkg::reset_lamb_servResponse_<std::allocator<void> > reset_lamb_servResponse;

typedef boost::shared_ptr< ::bboat_pkg::reset_lamb_servResponse > reset_lamb_servResponsePtr;
typedef boost::shared_ptr< ::bboat_pkg::reset_lamb_servResponse const> reset_lamb_servResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator1> & lhs, const ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator1> & lhs, const ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bboat_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bboat_pkg/reset_lamb_servResponse";
  }

  static const char* value(const ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct reset_lamb_servResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bboat_pkg::reset_lamb_servResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BBOAT_PKG_MESSAGE_RESET_LAMB_SERVRESPONSE_H
