// Generated by gencpp from file bboat_pkg/reset_vsb_serv.msg
// DO NOT EDIT!


#ifndef BBOAT_PKG_MESSAGE_RESET_VSB_SERV_H
#define BBOAT_PKG_MESSAGE_RESET_VSB_SERV_H

#include <ros/service_traits.h>


#include <bboat_pkg/reset_vsb_servRequest.h>
#include <bboat_pkg/reset_vsb_servResponse.h>


namespace bboat_pkg
{

struct reset_vsb_serv
{

typedef reset_vsb_servRequest Request;
typedef reset_vsb_servResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct reset_vsb_serv
} // namespace bboat_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bboat_pkg::reset_vsb_serv > {
  static const char* value()
  {
    return "c42a7ecd5bbbf1290f8a630b218058f2";
  }

  static const char* value(const ::bboat_pkg::reset_vsb_serv&) { return value(); }
};

template<>
struct DataType< ::bboat_pkg::reset_vsb_serv > {
  static const char* value()
  {
    return "bboat_pkg/reset_vsb_serv";
  }

  static const char* value(const ::bboat_pkg::reset_vsb_serv&) { return value(); }
};


// service_traits::MD5Sum< ::bboat_pkg::reset_vsb_servRequest> should match
// service_traits::MD5Sum< ::bboat_pkg::reset_vsb_serv >
template<>
struct MD5Sum< ::bboat_pkg::reset_vsb_servRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bboat_pkg::reset_vsb_serv >::value();
  }
  static const char* value(const ::bboat_pkg::reset_vsb_servRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bboat_pkg::reset_vsb_servRequest> should match
// service_traits::DataType< ::bboat_pkg::reset_vsb_serv >
template<>
struct DataType< ::bboat_pkg::reset_vsb_servRequest>
{
  static const char* value()
  {
    return DataType< ::bboat_pkg::reset_vsb_serv >::value();
  }
  static const char* value(const ::bboat_pkg::reset_vsb_servRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bboat_pkg::reset_vsb_servResponse> should match
// service_traits::MD5Sum< ::bboat_pkg::reset_vsb_serv >
template<>
struct MD5Sum< ::bboat_pkg::reset_vsb_servResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bboat_pkg::reset_vsb_serv >::value();
  }
  static const char* value(const ::bboat_pkg::reset_vsb_servResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bboat_pkg::reset_vsb_servResponse> should match
// service_traits::DataType< ::bboat_pkg::reset_vsb_serv >
template<>
struct DataType< ::bboat_pkg::reset_vsb_servResponse>
{
  static const char* value()
  {
    return DataType< ::bboat_pkg::reset_vsb_serv >::value();
  }
  static const char* value(const ::bboat_pkg::reset_vsb_servResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BBOAT_PKG_MESSAGE_RESET_VSB_SERV_H
